### ISSUE TITLE
Users can't create alternate profiles

### ISSUE THREAD

**Issue by SigmasonicX** [Figments/pulp-fiction#698]
User reported
![image](https://user-images.githubusercontent.com/71996084/136669784-99d59d12-98d0-44c7-a93d-e3ad1d91c5bf.png)

Attempting to create a new profile results in an error
[Nest] 30256  - 10/09/2021, 11:12:25 AM   ERROR [ExceptionsHandler] Account validation failed: _id: Error, expected `_id` to be unique. Value: `mWAISEGo54xUQg2K9BEFD`
ValidationError: Account validation failed: _id: Error, expected `_id` to be unique. Value: `mWAISEGo54xUQg2K9BEFD`

**Comment by Figments** [comment]
this was fixed in a previous update. see #695
