### ISSUE TITLE
Creating new chapter after navigating to an existing chapter populates new chapter form with that chapter's data

### ISSUE THREAD

**Issue by SigmasonicX** [Figments/pulp-fiction#730]
User reported
Think it's been this way since the last big update couple weeks ago. Might be similar actions that break it this way, but I hadn't been paying attention when it first happened to me (when I started this fic)

1. navigate to one of my works
2. click on a (published?) chapter
3. hit the back button
4. click "add chapter"
expected result: a blank create-section form
actual result: form has all the data from the chapter I had clicked on

workaround: after hitting the back button, reload the page

**Comment by Figments** [comment]
no longer an issue
