### ISSUE TITLE
Integrate Search into Browse

### ISSUE THREAD

**Issue by SigmasonicX** [Figments/pulp-fiction#753]
From Figments:
i think at some point it would be a good idea to integrate search into this
put like a search field at the top with a dropdown for advanced options
that way "finding content" is all in one space

![image](https://user-images.githubusercontent.com/71996084/142463646-96a7270a-3d46-49dc-b2ed-980d3f11fcac.png)

**Comment by Figments** [comment]
search now has its own dedicated page and complete styling, this is no longer relevant
