### ISSUE TITLE
Improve load times on My Library

### ISSUE THREAD

**Issue by SigmasonicX** [Figments/pulp-fiction#758]
Currently, My Library loads the work cards for every work in the library at once. In my case, the content-library/fetch call was 8.87 MB. The cleanest solution would be to use pagination.

![image](https://user-images.githubusercontent.com/71996084/143389959-cad331de-89f5-4603-9b90-8b7a13cfab0b.png)

**Comment by Figments** [comment]
load times have been improved across the board as of the latest update
