### ISSUE TITLE
Proposal - Side menu has "Create" button that links to page for creating a new work

### ISSUE THREAD

**Issue by SigmasonicX** [Figments/pulp-fiction#761]
We've seen multiple users have trouble finding where to create works. While one was due to a bug with small profile pictures (#759), the other was a user not thinking to check the profile to create a work.

My proposal is to add a "Create" button to the side menu, perhaps using a pencil icon. When clicked, this will produce a submenu with three links: Create Prose, Create Poetry, and Create Blog. This will produce the corresponding form (or go to the corresponding page, if we switch back to them being separate pages).

When the form is completed, it should take you to the profile page, on the drafts tab.

**Comment by Figments** [comment]
this feature is now in place
