### ISSUE TITLE
"ERROR [IdentityGuard] Someone attempted to impersonate User" when on Add Profile screen (inconsistent)

### ISSUE THREAD

**Issue by SigmasonicX** [Figments/pulp-fiction#783]
When on the Add Profile screen, I sometimes encounter this error
ERROR [IdentityGuard] Someone attempted to impersonate User VRGqiB6BNFu-ZWRb1_5br!

This appears to be connected to errors when generating a new pseudonym

**Comment by Figments** [comment]
this should no longer happen
